LBPM/urls.py
from django.urls import path

from . import views


#urlpatterns = patterns('LBPM.views',
#    url(r'^list/$', 'list', name='list'),
#)

urlpatterns = [
    path('index', views.index, name='index'),
    path('preview', views.preview_image, name='preview'),
    path('input', views.get_input, name='input'),
    path('image_labels', views.get_image_labels, name='image_labels'),
    path('image', views.get_image, name='image'),
    path('color', views.get_color_with_domain, name='color'),
    path('simulation', views.simulation, name='simulation'),
    path('list', views.list, name='list'),
    #path('list/<int:year>/', views.year_archive),
    #path('input', views.simulation, name='input'),
]

RockSimPortal/urls.py
import os
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls import include, url
from django.conf import settings
#from django.urls import re_path
#from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('project/', include('upload.urls')),
    path('LBPM/', include('LBPM.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    #re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    #path('media/','django.views.static.serve','media'),
    #url(r'^media/$',media,name='media'),
 ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path
from django.urls import include, re_path
#from django.conf.urls import include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('index', views.index, name='index'),
    path('upload', views.dataset_image_upload, name='upload'),
    #path('my_projects',views.my_projects, name='my_projects'),
    re_path(r'^my/$', views.my_projects, name='my_projects'),

    re_path(r'^(?P<project_id>\d+?)/?$', views.view_project, name='view_project'),

    re_path(r'^(?P<project_id>\d+?)/datasets/$',
        views.project_add_dataset, name="project_add_dataset"),

    re_path(r'^(?P<project_id>\d+?)/origin_data/(?P<origin_data_id>\d+?)/edit/$',
        views.origin_edit_metadata, name="origin_data_edit"),

    re_path(r'^new/$', views.create_project, name='create_project'),

    re_path(r'^(?P<project_id>\d+?)/sample/new/$',
        views.add_sample, name="add_sample"),

    re_path(r'^(?P<project_id>\d+?)/sample/(?P<sample_id>\d+?)/$',
        views.view_sample, name="view_sample"),

    re_path(r'^(?P<project_id>\d+?)/images/(?P<image_id>\d+)/edit/$',
        views.edit_dataset_image, name='edit_dataset_image'),

    re_path(r'^(?P<project_id>\d+?)/sample/(?P<sample_id>\d+?)/edit/$',
        views.edit_sample, name="edit_sample"),

    re_path(r'^(?P<project_id>\d+?)/edit/$', views.project_edit_metadata, name='edit_project'),
    re_path(r'^(?P<project_id>\d+?)/collaborators/$', views.add_collaborator, name="project_add_collaborator"),

    re_path(r'^(?P<project_id>\d+?)/collaborators/(?P<collaborator_id>\d+?)/remove/$',
        views.remove_collaborator, name="project_remove_collaborator"),

    re_path(r'^(?P<project_id>\d+?)/collaborators/(?P<collaborator_id>\d+?)/status/$',
        views.update_collab_status, name="update_collab_status"), 

    re_path(r'^(?P<project_id>\d+?)/origin_data/(?P<origin_data_id>\d+?)/$',
        views.origin_data_summary, name="origin_data_summary"),

    re_path(r'^(?P<project_id>\d+?)/origin_data/(?P<origin_data_id>\d+?)/upload/$',
        views.dataset_image_upload, name="origin_data_image_upload"),
    re_path(r'^(?P<project_id>\d+?)/origin_data/(?P<origin_data_id>\d+?)/uploadNI/$',
        views.dataset_nonimage_upload, name="origin_data_nonimage_upload"),

   #path('simulation', views.simulation, name='simulation'),
    #path('input', views.simulation, name='input'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#   re_path(r'^$', views.browse_projects, name='browse_projects'),


#    re_path(r'^(?P<project_id>\d+?)/origin_data/(?P<origin_data_id>\d+?)/edit/$',
#        views.origin_edit_metadata, name="origin_data_edit"),

upload/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User as MyUser
from django.urls import reverse

from .api import (
    ProjectMapping,
    SampleMapping,
    OriginDataMapping,
    AnalysisDataMapping,
    DatafileMapping,
)

#class MyUser(AbstractUser):
    # Notice that we are inheriting from AbstractUser. Therefore, we                                                            
    # get all the default fields for free.                                                                                      
#    organization = models.CharField(max_length=255, default="")
#    name_identifier = models.CharField(max_length=255, default="")
#    identifier_scheme = models.CharField(max_length=255, default="")
#    scheme_uri = models.CharField(max_length=255, default="")

#    def full_name(self):
#        return '%s %s' % (self.first_name, self.last_name)

#    def official_name(self):
#        return '%s, %s' % (self.last_name, self.first_name)

#    def APA_name(self):  # pylint: disable=invalid-name                                                                       #  
#        return '%s, %s.' % (self.last_name, self.first_name[0])

#    def IEEE_name(self):  # pylint: disable=invalid-name                                                                      #  
#        return '%s. %s' % (self.first_name[0], self.last_name)
#
#    def __unicode__(self):
#        return '%s (%s)' % (self.full_name(), self.organization)

def project_cover_pic_path(instance, filename):
    return '/'.join(['projects', str(instance.id), 'cover_pic', filename])


# Create your models here.
IMAGE_TYPES = (
    ('8-bit', '8-bit'),
    ('16-bit Signed', '16-bit Signed'),
    ('16-bit Unsigned', '16-bit Unsigned'),
    ('32-bit Signed', '32-bit Signed'),
    ('32-bit Unsigned', '32-bit Unsigned'),
    ('32-bit Real', '32-bit Real'),
    ('64-bit Real', '64-bit Real'),
    ('24-bit RGB', '24-bit RGB'),
    ('24-bit RGB Planar', '24-bit RGB Planar'),
    ('24-bit BGR', '24-bit BGR'),
    ('24-bit Integer', '24-bit Integer'),
    ('32-bit ARGB', '32-bit ARGB'),
    ('32-bit ABGR', '32-bit ABGR'),
    ('1-bit Bitmap', '1-bit Bitmap'),
)


BYTE_ORDERS = (
    ('big-endian', 'Big endian'),
    ('little-endian', 'Little endian'),
)

class project(models.Model):  # pylint: disable=invalid-name
    # Name of the project and user should be primary key,
    # but a composite primary key is not supported by
    # Django. Therefore, we would define a unique key
    # constraint for this.
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    creation_date = models.DateField()
    description = models.TextField()
    cover_pic = models.ImageField(upload_to=project_cover_pic_path, blank=True)
    #access = models.IntegerField(default=2, choices=ACCESS)
    #institution = models.CharField(max_length=255)
    #doi = models.CharField(max_length=512, blank=True)
    #ark = models.CharField(max_length=512, blank=True)
    #license = models.IntegerField(default=0, choices=LICENSES)
    #num_downloads = models.IntegerField(default=0)

    class Meta:
        unique_together = ("user", "name",)
        ordering = ('name', '-creation_date', )

    def __unicode__(self):
        return self.name

    #@property
    #def doi_clean(self):
    #    doi = self.doi.strip()
    #    if self.doi.strip().startswith('doi:'):
    #        doi = doi.replace('doi:', '', 1)
    #    return doi

    def is_viewable_by_user(self, user):
        return True
    #    if user.is_superuser:
    #        return True
    #    elif user.has_perm('upload.change_project'):
    #        return True
    #    elif (self.access == 1 or
    #          user == self.user or
    #          self.is_collaborator(user)):
    #        return True
    #    return False

    def is_editable_by_user(self, user):
        return True
    #    if user.is_superuser:
    #         return True
    #     elif user.has_perm('upload.change_project'):
    #         return True
    #     elif (self.access == 2 and
    #           (user == self.user or
    #            self.is_collaborator(user))):
    #         return True
    #     return False

    def is_collaborator(self, user):
        return True
    #    for collab in self.collaborators.all():
    #        if user == collab.user:
    #            return True
    #    return False

    def delete(self, *args, **kwargs):
        # self._ezid_doi_delete()
        super(project, self).delete(*args, **kwargs)

    def origin_data_without_sample(self):
        return self.origin_data.filter(sample=None)

    # pylint: disable=invalid-name
    def analysis_data_without_sample_or_origin(self):
        return self.analysis_data.filter(sample=None, base_origin_data=None)


def project_file_path(instance, filename):
    project_id = instance.project.id
    dataset_type = 'origin'
    dataset_id = instance.origin_data.id

    return '/'.join([
        'projects',
        str(project_id),
        dataset_type,
        str(dataset_id),
        'images',
        filename
    ])


class sample(models.Model):
    SOURCES = (
        ('N', 'Natural'),
        ('A', 'Artificial')
    )

    POROUS_MEDIA_TYPE = (('SAND', 'Sandstone'),
                         ('SOIL', 'Soil'),
                         ('CARB', 'Carbonate'),
                         ('GRAN', 'Granite'),
                         ('BEAD', 'Beads'),
                         ('FIBR', 'Fibrous Media'),
                         ('COAL', 'Coal'),
                         ('OTHE', 'Other'))

    name = models.CharField(max_length=255)
    description = models.TextField()

    project = models.ForeignKey(project, related_name='samples', on_delete=models.CASCADE)
    uploader = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    porous_media_type = models.CharField(
        max_length=50,
        choices=POROUS_MEDIA_TYPE
    )
    porous_media_other_description = models.CharField(
        max_length=255, null=True, blank=True,
        help_text='Other porous media type description.',
    )
    source = models.CharField(max_length=50, choices=SOURCES)
    grain_size_min = models.FloatField(null=True, blank=True)
    grain_size_max = models.FloatField(null=True, blank=True)
    grain_size_avg = models.FloatField(null=True, blank=True)
    porosity = models.FloatField(null=True, blank=True)
    identifier = models.CharField(max_length=255, null=True, blank=True)
    geographic_origin = models.CharField(
        max_length=50, null=True, blank=True,
        help_text=(
            'The geographic location, latitude/longitude, '
            'from which the sample was obtained.'
        ),
    )
    location = models.CharField(
        max_length=50, null=True, blank=True,
        help_text=(
            'This should be the current location of the sample. '
            'For example: which campus, building number, '
            'room number, and/or cabinet number.'
        ),
    )

    class Meta:
        unique_together = ("name", "project")

    def __unicode__(self):
        return self.name


class origin_data(models.Model):
    name = models.CharField(max_length=255)
    project = models.ForeignKey(project, related_name='origin_data', on_delete=models.CASCADE)
    sample = models.ForeignKey(
        sample,
        null=True,
        blank=True,
        help_text=(
            'Each data-set is associated with '
            'actual physical sample. Choose one of the existing '
            'sample, or add details for a new sample later.'
        ),
        related_name='origin_data',
        on_delete=models.CASCADE
    )
    uploader = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    is_segmented = models.IntegerField(
        choices=(
            (1, 'Yes'),
            (2, 'No')
        ),
        default=1
    )
    external_url = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='External URI'
        )
    voxel_x = models.FloatField(null=True, blank=True)
    voxel_y = models.FloatField(null=True, blank=True)
    voxel_z = models.FloatField(null=True, blank=True)
    voxel_units = models.CharField(
        max_length=50,
        blank=True,
        choices=(
            ('nm', 'nanometer'),
            ('um', 'micrometer'),
            ('mm', 'millimeter'),
            ('other', 'other (specify)')
            )
        )

    voxel_other = models.CharField(max_length=50, null=True, blank=True)
    provenance = models.TextField(verbose_name='Description')
    doi = models.CharField(max_length=255, blank=True)

    class Meta:
        # This is a caution, we don't have sample inside here.
        # This is intentional as we could have *unknown* sample.
        unique_together = ("name", "project",)
        verbose_name = 'Origin Data'
        verbose_name_plural = 'Origin Data'

    def __unicode__(self):
        return self.name


class analysis_data(models.Model):
    ANALYSIS_DATA_TYPE = (('Simulation', 'Simulation'),
                          ('GeometricAnalysis', 'Geometric Analysis'),
                          ('Other', 'Other'))

    name = models.CharField(max_length=255)
    type = models.CharField(max_length=50, choices=ANALYSIS_DATA_TYPE)

    project = models.ForeignKey(project, related_name='analysis_data', on_delete=models.CASCADE)
    sample = models.ForeignKey(sample, blank=True, null=True,
                               related_name='analysis_data', on_delete=models.CASCADE)
    uploader = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    external_url = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='External URI'
        )

    base_origin_data = models.ForeignKey(origin_data, blank=True, null=True,
                                         related_name='analysis_data', on_delete=models.CASCADE)
    base_analysis_data = models.ForeignKey(
        "analysis_data",

upload/templates/upload/project/dataset/analysis_edit.html
{% extends "upload/project/base.html" %}

{% load bootstrap3 %}

{% block title %}Edit {{dataset.name}} - Analysis Data - {{project_obj.name}} - Project{% endblock %}

{% block project %}
<section class="dataset-metadata">
  <header>
    <h2>Edit {{dataset.name}} <small>Analysis Data</small></h2>
  </header>

  <form method="post">
    {% csrf_token %}

    {% bootstrap_form form %}

    <div class="form-actions">
      <button type="submit" name="save" class="btn btn-primary">Save changes</button>
      <a href="{{ dataset_url }}" class="btn btn-link">Cancel</a>
      <button type="submit" name="delete" value="delete" class="btn btn-danger pull-right">Delete dataset</button>
    </div>
  </form>
</section>
{% endblock %}
{% block javascript_block %}
<script>
  (function(window, $) {
    $('button[name="delete"]').on('click', function(e) {
      if (! window.confirm('Are you sure you want to delete this record? This action cannot be undone.')) {
        e.preventDefault();
      }
    });
  })(window, jQuery);
</script>
{% endblock %}

upload/templates/upload/project/dataset/edit_sample.html
{% extends "upload/project/base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block title %} Edit Sample {{ sample.name }} - {{ project_obj.name }} {% endblock %}

{% block project %}
  <h2>{{ sample.name }} <small>Edit Sample Data</small></h2>

  <div class="row">
    <div class="col-md-3 col-md-push-9">
      <!--
      <div class="well well-sm">
        <h3>Help text here.</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dignissim facilisis mi ut ultrices. Quisque dignissim arcu quis orci sagittis aliquam. Fusce interdum mauris eget velit mattis tempor. Aenean condimentum quam enim. Nullam a lectus sit amet tortor suscipit interdum. Curabitur laoreet euismod justo, a fermentum nunc laoreet sed. Phasellus pharetra nec nunc id hendrerit. Quisque ornare, purus et semper scelerisque, eros lacus ultrices metus, vitae fermentum quam lectus at nisi.
        </p>
      </div>
      -->
    </div>
    <div class="col-md-9 col-md-pull-3">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form %}

        <div class="actions">
          <button type="submit" class="btn btn-primary">Save Sample Data</button>
          <a href="{% url 'view_sample' sample.project.id sample.id %}" class="btn btn-link">Cancel</a>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block javascript_block %}
<script>
(function(window, $, undefined) {
  $('#id_porous_media_type').on('change', function() {
    if (this.value === 'OTHE') {
      $('#id_porous_media_other_description').parent().removeClass('hide');
    } else {
      $('#id_porous_media_other_description').parent().addClass('hide');
    }
  });
  $('#id_porous_media_type').trigger('change');
})(window, jQuery);
</script>
{% endblock %}

upload/templates/upload/project/dataset/image_upload.html
{% extends "upload/project/base.html" %}

{% block title %}Upload Image Data - {{dataset.name}} - {{project_obj.name}}{% endblock %}

{% block project %}

<h2>
  {{dataset.name}} <small>Upload Image Data</small>
</h2>

<h4>Upload Options</h4>
<form method="post" name="upload-form" id="id_upload-form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="upload-options row">
      <div class="col-md-4 col-xs-12">
        <span class="fileinput-button btn btn-primary btn-lg btn-block btn-filechooser">
          <i class="glyphicon glyphicon-file"></i> Choose files from computer
          <input type="file" name="images" id="id_images" multiple>
        </span>
      </div>
    </div>
  </div>

  <div class="actions text-center fileupload-buttonbar">
    <button type="submit" class="btn btn-lg btn-primary start">Upload Files</button>
    <a href="{{dataset_view_url}}" class="btn btn-link cancel">Back to dataset</a>
  </div>

</form>
{% endblock %}

{% block javascript_block %}
<script type="text/javascript" src="{{STATIC_URL}}vendor/blueimp-tmpl/js/tmpl.js"></script>
<script id="template-upload" type="text/x-tmpl">
  <tr class="template-upload fade <% if (o.file.source === 'Local file') { %>local-upload<%} else { %>cloud-upload<% } %>">
    <td>
      <p><%=o.file.source%></p>
      <input type="hidden" name="source" id="id_source" value="<%=o.file.source%>">
      <input type="hidden" name="name" id="id_name" value="<%=o.file.name%>">
      <input type="hidden" name="size" id="id_size" value="<%=o.file.size%>">
      <input type="hidden" name="url" id="id_url" value="<%=o.file.url%>">
      <input type="hidden" name="basic" id="id_basic" value="<%=o.file.standardImage%>">
    </td>
    <td>
      <p class="name"><%=o.file.name%> <small class="text-muted"><%=o.file.sizeFmt%></small></p>
      <div class="form-horizontal <% if (o.file.standardImage) { %>hide<% }%>">
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="control-label col-sm-3" for="id_image_type">Image type</label>
          <div class="col-sm-9">
          <select id="image_type" name="image_type" id="id_image_type" class="form-control">
            <option value="">Choose one</option>
            <option value="8-bit">8-bit</option>
            <option value="16-bit Signed">16-bit Signed</option>
            <option value="16-bit Unsigned">16-bit Unsigned</option>
            <option value="32-bit Signed">32-bit Signed</option>
            <option value="32-bit Unsigned">32-bit Unsigned</option>
            <option value="32-bit Real">32-bit Real</option>
            <option value="64-bit Real">64-bit Real</option>
            <option value="24-bit RGB">24-bit RGB</option>
            <option value="24-bit RGB Planar">24-bit RGB Planar</option>
            <option value="24-bit BGR">24-bit BGR</option>
            <option value="24-bit Integer">24-bit Integer</option>
            <option value="32-bit ARGB">32-bit ARGB</option>
            <option value="32-bit ABGR">32-bit ABGR</option>
            <option value="1-bit Bitmap">1-bit Bitmap</option>
          </select>
          </div>
        </div>
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="col-sm-3 control-label" for="id_width">Width</label>
          <div class="col-sm-9">
          <input type="text" class="form-control" name="width" id="id_width" placeholder="width">
          <p class="help-block">Number of voxels in the X-direction</p>
          </div>
        </div>
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="col-sm-3 control-label" for="id_height">Height</label>
          <div class="col-sm-9">
          <input type="text" class="form-control" name="height" id="id_height" placeholder="height">
          <p class="help-block">Number of voxels in the Y-direction</p>
          </div>
        </div>
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="col-sm-3 control-label" for="id_numberofImages">Number of images</label>
          <div class="col-sm-9">
          <input type="text" class="form-control" name="numberOfImages" id="id_numberofImages" placeholder="number of images">
          <p class="help-block">Number of voxels in the Z-direction</p>
          </div>
        </div>
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="col-sm-3 control-label" for="id_offsetToFirstImage">Offset to first image</label>
          <div class="col-sm-9">
          <input type="text" class="form-control" name="offsetToFirstImage" id="id_offsetToFirstImage" placeholder="offset" value="0">
          </div>
        </div>
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="col-sm-3 control-label" for="id_gapBetweenImages">Gap between images</label>
          <div class="col-sm-9">
          <input type="text" class="form-control" name="gapBetweenImages" id="id_gapBetweenImages" placeholder="gap" value="0">
          </div>
        </div>
        <div class="form-group <% if (o.file.isArchive==false) { %>required<% }%>">
          <label class="col-sm-3 control-label" for="id_byteOrder">Byte order</label>
          <div class="col-sm-9">
          <select class="form-control" name="byteOrder" id="id_byteOrder">
            <option value="">Choose one</option>
            <option value="big-endian">Big endian</option>
            <option value="little-endian">Little endian</option>
          </select>
          <p class="help-block">Big endian and little endian refers to the direction data (each bit in a byte of data, that is) was written in the binary array you are uploading. This depends on the machine that wrote the original data file. If you don&#39;t know this information, wait until the upload is done and review resulting .jpg or .gif files. Mixing up endian-ness of your data is one of the reasons why your data will not look right at the end of the upload, so change it as necessary.</p>
          </div>
        </div>
      </div>
    </td>
    <td>
      <button class="btn btn-warning btn-sm cancel" tabindex="-1">
        <i class="glyphicon glyphicon-ban-circle"></i>
        <span class="sr-only">Cancel</span>
      </button>
    </td>
  </tr>
</script>
<script type="text/javascript" src="{{STATIC_URL}}vendor/blueimp-file-upload/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}vendor/blueimp-file-upload/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}upload/js/csrf.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script><!--TODO: put this lib in static folder-->
<script type="text/javascript" src="{{STATIC_URL}}upload/js/image-upload.js"></script>
{% endblock %}

upload/templates/upload/project/dataset/nonimage_upload.html
{% extends "upload/project/base.html" %}

{% block title %}Upload Non-Imagge Data - {{dataset.name}} - {{project_obj.name}}{% endblock %}

{% block project %}

<h2>
  {{dataset.name}} <small>Upload Non-Image Data</small>
</h2>
<p class="lead">
  You can upload image data from your personal computer or transfer files already
  uploaded to
  <a style="white-space:nowrap" href="https://dropbox.com" rel="nofollow" target="_blank">Dropbox <i class="glyphicon glyphicon-link"></i></a>
  or
  <a style="white-space:nowrap" href="https://box.com" rel="nofollow" target="_blank">Box.com <i class="glyphicon glyphicon-link"></i></a>.
</p>

<h4>Upload Options</h4>
<form method="post" name="upload-form" id="id_upload-form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="upload-options row">
      <div class="col-md-4 col-xs-12">
        <span class="fileinput-button btn btn-primary btn-lg btn-block btn-filechooser">
          <i class="glyphicon glyphicon-file"></i> Choose files from computer
          <input type="file" name="images" id="id_images" multiple>
        </span>
      </div>
      <div class="col-md-4 col-xs-6">
        <button class="btn btn-lg btn-default btn-block btn-dropbox" name="dropbox-upload" id="id_dropbox-upload" type="button">
          <span class="sr-only">Dropbox</span>
        </button>
      </div>
      <div class="col-md-4 col-xs-6">
        <button class="btn btn-lg btn-default btn-block btn-box" type="button">
          <span class="sr-only">Box.com</span>
        </button>
      </div>
    </div>
  </div>
  <p class="help-block text-center">
    You can drag-and-drop files from your computer to
    this page to upload.
  </p>

  <div class="table-responsive">
    <table class="table table-bordered"><tbody class="files"></tbody></table>
  </div>

  <div class="upload-progress hide">
    <div class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
        <span class="sr-only">0% Complete</span>
      </div>
    </div>
  </div>

  <div class="actions text-center fileupload-buttonbar">
    <button type="submit" class="btn btn-lg btn-primary start" disabled>Upload Files</button>
    <a href="{{dataset_view_url}}" class="btn btn-link cancel">Back to dataset</a>
  </div>

</form>
{% endblock %}

{% block javascript_block %}
<script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key="{{dropbox_app_key}}"></script>
<script type="text/javascript" src="https://app.box.com/js/static/select.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}vendor/blueimp-tmpl/js/tmpl.js"></script>
<script id="template-upload" type="text/x-tmpl">
  <tr class="template-upload fade <% if (o.file.source === 'Local file') { %>local-upload<%} else { %>cloud-upload<% } %>">
    <td>
      <p><%=o.file.source%></p>
      <input type="hidden" name="source" id="id_source" value="<%=o.file.source%>">
      <input type="hidden" name="name" id="id_name" value="<%=o.file.name%>">
      <input type="hidden" name="size" id="id_size" value="<%=o.file.size%>">
      <input type="hidden" name="url" id="id_url" value="<%=o.file.url%>">
      <input type="hidden" name="basic" id="id_basic" value="<%=o.file.standardImage%>">
    </td>
    <td>
      <button class="btn btn-warning btn-sm cancel">
        <i class="glyphicon glyphicon-ban-circle"></i>
        <span class="sr-only">Cancel</span>
      </button>
    </td>
  </tr>
</script>
<script type="text/javascript" src="{{STATIC_URL}}vendor/blueimp-file-upload/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}vendor/blueimp-file-upload/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}upload/js/csrf.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}upload/js/image-upload.js"></script>
{% endblock %}